/* Generated by tools/extract_sfx.py — do not edit. */
#include "sfx_data.h"

const SfxEntry SFX_BANK[SFX_COUNT] = {
  {      0,   1888,  428 },  /* FIRE */
  {   1888,  10966,  428 },  /* HIT */
  {  12854,  21690,  428 },  /* DEATH */
  {  34544,  17844,  428 },  /* ZAP */
  {  52388,  22934,  188 },  /* EXC */
};
