// Generated by tools/extract_sfx.py — do not edit.
//
// Tempest 2000 SFX bank, pre-converted to RF5C164 sign-magnitude.
// The raw bytes live in res/sfx_data.bin and are .incbin'd into the
// cart ROM by res.s as res_sfx_data; at boot, mcd_upload_sfx_bank
// copies them to PRG-RAM at SFX_PRG_BASE and ships SFX_BANK[] to
// the sub via CMD_INIT_SFX_BANK so the sub can dereference them.

#ifndef SFX_DATA_H
#define SFX_DATA_H

#include <types.h>

#define SFX_COUNT       5
#define SFX_BLOB_BYTES  75322

/* PRG-RAM addresses the cart writes to / the sub reads from.
 * SFX_PRG_BASE is where the byte blob starts (sub dereferences
 * SFX_PRG_BASE + SFX_BANK[idx].offset for sample data).
 * SFX_META_PRG is where the SfxEntry[] table lives (sub reads
 * `((const SfxEntry *) SFX_META_PRG)[idx]`). Both are in PRG-RAM
 * bank 0; the cart accesses them via the window at $420000 + off. */
#define SFX_PRG_BASE    0x01100u
#define SFX_META_PRG    0x0F000u

/* Per-SFX metadata. Offsets are relative to SFX_PRG_BASE (so the
 * sub computes data_ptr = SFX_PRG_BASE + offset). period feeds
 * pcm_set_period (428 ≈ 8363 Hz, 188 ≈ 19 kHz). */
typedef struct {
  u16 offset;
  u16 length;
  u16 period;
} SfxEntry;

extern const SfxEntry SFX_BANK[SFX_COUNT];

#define SFX_IDX_FIRE    0
#define SFX_IDX_HIT     1
#define SFX_IDX_DEATH   2
#define SFX_IDX_ZAP     3
#define SFX_IDX_EXC     4

#endif
