// Generated by tools/extract_mcd_sprites.py — do not edit.
// Polygon-rasterised entity sprites from tempest2k-source/src/obj2d.s,
// each 8x8 or 16x16 in MD 4bpp tile format, column-major.

#ifndef TEMPEST_SPRITES_H
#define TEMPEST_SPRITES_H

#include <types.h>

extern const u8 SPR_FLIPPER_T0_F0[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T0_F1[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T0_F2[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T0_F3[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T1_F0[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T1_F1[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T1_F2[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T1_F3[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T2_F0[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T2_F1[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T2_F2[32];  /* 1x1, pal 2 */
extern const u8 SPR_FLIPPER_T2_F3[32];  /* 1x1, pal 2 */
extern const u8 SPR_SHOT[32];  /* 1x1, pal 1 */
extern const u8 SPR_PLAYER_L00[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L01[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L02[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L03[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L04[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L05[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L06[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L07[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L08[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L09[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L10[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L11[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L12[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L13[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L14[128];  /* 2x2, pal 4 */
extern const u8 SPR_PLAYER_L15[128];  /* 2x2, pal 4 */

#endif
